plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

base {
	archivesName = "humanbot-mc${project.minecraft_version}"
}

repositories {
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
	def version = project.version
	def mcDep = project.minecraft_dep
	inputs.property "version", version
	inputs.property "mcDep", mcDep
	filesMatching("fabric.mod.json") {
		expand "version": version, "mcDep": mcDep
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
	it.options.encoding = "UTF-8"
}

java {
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}
